
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS Usuarios (
    Id UUID PRIMARY KEY DEFAULT uuid_generate_v4()
);


CREATE TABLE IF NOT EXISTS Livros (
    Id UUID PRIMARY KEY DEFAULT uuid_generate_v4()
);
ALTER TABLE Livros ADD COLUMN IF NOT EXISTS DataInsert TIMESTAMP DEFAULT NOW();
ALTER TABLE Livros ADD COLUMN IF NOT EXISTS ISBN VARCHAR(20);
ALTER TABLE Livros ADD COLUMN IF NOT EXISTS Titulo VARCHAR(255);
ALTER TABLE Livros ADD COLUMN IF NOT EXISTS QuantidadePaginas INTEGER DEFAULT 0;
ALTER TABLE Livros ADD COLUMN IF NOT EXISTS AnoPublicacao INTEGER DEFAULT 0;
ALTER TABLE Livros ADD COLUMN IF NOT EXISTS Descricao TEXT;
ALTER TABLE Livros ADD COLUMN IF NOT EXISTS Categorias VARCHAR(255)[];
ALTER TABLE Livros ADD COLUMN IF NOT EXISTS Autores VARCHAR(255)[];
ALTER TABLE Livros ADD COLUMN IF NOT EXISTS Imagens JSONB;

CREATE TABLE IF NOT EXISTS UsuariosLivros (
    Id UUID PRIMARY KEY DEFAULT uuid_generate_v4()
);
ALTER TABLE UsuariosLivros ADD COLUMN IF NOT EXISTS IdLivro UUID DEFAULT NULL;
ALTER TABLE UsuariosLivros ADD COLUMN IF NOT EXISTS IdUsuario UUID DEFAULT NULL;
ALTER TABLE UsuariosLivros ADD COLUMN IF NOT EXISTS DataInsert TIMESTAMP DEFAULT NOW();
ALTER TABLE UsuariosLivros ADD COLUMN IF NOT EXISTS PaginasLidas INTEGER DEFAULT 0;

CREATE TABLE IF NOT EXISTS Comentarios (
    Id UUID PRIMARY KEY DEFAULT uuid_generate_v4()
);
ALTER TABLE Comentarios ADD COLUMN IF NOT EXISTS IdLivro UUID DEFAULT NULL;
ALTER TABLE Comentarios ADD COLUMN IF NOT EXISTS IdUsuario UUID DEFAULT NULL;
ALTER TABLE Comentarios ADD COLUMN IF NOT EXISTS DataInsert TIMESTAMP DEFAULT NOW();
ALTER TABLE Comentarios ADD COLUMN IF NOT EXISTS Comentario text DEFAULT NULL;